apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mysql
  labels:
    type: labels 
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.159.134
    path: "/srv/nfs/kubedata"