apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginxsvc-ingress
spec:
  rules:
  - host: nginxsvc.com
    http:
      paths:
      - backend:
          serviceName: nginx-deployment-75ccf4894d-sngbs
          servicePort: 80

