apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-ingress-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ingress-nginx
  template:
    metadata:
      labels:
        name: nginx-ingress
  spec:
     containers:
       - name: nginx-ingress-controller
         image: quay.io/kubernetes-ingress-
                controller/nginx-ingress-controller:0.21.0
  args:
     - /nginx-ingress-controller
     - --configmap=$(nginx-7bb7cd8db5-hbpxk) /nginx-configuration
  env:
    - name: nginx-7bb7cd8db5-hbpxk
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name : ingress-nginx
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
  ports:
    - name: http
      containerPort: 80
    - name: https
      containerPort: 443